include(GNUInstallDirs)

install(
  TARGETS JASP JASPEngine
  RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR}
  LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR}
  ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR}
  BUNDLE DESTINATION ${CMAKE_INSTALL_LIBDIR}/Bundle)

install(DIRECTORY ${CMAKE_SOURCE_DIR}/Resources
        DESTINATION ${CMAKE_INSTALL_BINDIR})
