#Used for common JASP qmake build settings

#Jasp-R-Interface
JASP_R_INTERFACE_TARGET = JASP-R-Interface
JASP_R_INTERFACE_MAJOR_VERSION = 1 # Interface changes
JASP_R_INTERFACE_MINOR_VERSION = 0 # Code changes
JASP_R_INTERFACE_NAME = $$JASP_R_INTERFACE_TARGET$$JASP_R_INTERFACE_MAJOR_VERSION

#R settings
CURRENT_R_VERSION = 3.3
