#ifndef DYNAMICRUNTIMEENUMS_H
#define DYNAMICRUNTIMEENUMS_H
#include "enumutilities.h"

DECLARE_ENUM( RuntimeEnvironment,	ZIP, MSIX, MSI, R, FLATPAK, MAC, LINUX_LOCAL, UNKNOWN );
DECLARE_ENUM( MicroArch,			 AARCH64, X86_64, UNSUPPORTED );

#endif // DYNAMICRUNTIMEENUMS_H
