#ifndef DYNAMICRUNTIMEENUMS_H
#define DYNAMICRUNTIMEENUMS_H
#include "enumutilities.h"

DECLARE_ENUM( RuntimeEnvironment,		UNKNOWN, ZIP, MSIX, MSI, R, FLATPAK, MAC, LINUX_LOCAL );
DECLARE_ENUM( MicroArch,				UNSUPPORTED, AARCH64, X86_64  );

#endif // DYNAMICRUNTIMEENUMS_H
