.TH "JASP" "1" "September 2016" "Michael Hanke" ""
.SH "NAME"
JASP \-  Bayesian statistics made accessible
.SH "DESCRIPTION"
JASP aims to be a complete statistical package for both Bayesian and
Frequentist statistical methods, that is easy to use and familiar to users of
SPSS.
.PP
JASP comes with a handful of example data sets, which can be accessed from the
File tab. Selecting these will load up the data, allowing you to inspect and
analyse it.
.PP
JASP can also open data sets in the .csv (comma separated volume) data format.
In practice, .csv files are often delimitered with a range of different
characters and not just commas. When opening a .csv file, JASP examines the
file, and automatically determines what the delimiters are. This usually means
that JASP can open any .csv file without intervention from the user. The only
absolute requirement, is that the .csv file contains a header row; where the
names of each of the columns appear in the first row.

.SH "SEE ALSO"
The JASP homepage at
.I https://jasp-stats.org
.SH "AUTHOR"
JASP is developed as free software by a group headed by Eric-Jan
Wagenmakers.
.PP
This manual page was written by Michael Hanke <mih@debian.org>,
for the Debian project (but may be used by others).
