#ifndef VERSION_H
#define VERSION_H

#define APP_VERSION "JASP 0.7 Alpha"
#define APP_VERSION_MASSIVE  1
#define APP_VERSION_MAJOR    0
#define APP_VERSION_MINOR    7
#define APP_VERSION_REVISION 0
#define APP_VERSION_RELEASE_TYPE "Alpha"

#endif // VERSION_H
