#ifndef VERSION_H
#define VERSION_H

#define APP_VERSION "JASP 0.6.6 Alpha"
#define APP_VERSION_MASSIVE  1
#define APP_VERSION_MAJOR    0
#define APP_VERSION_MINOR    6
#define APP_VERSION_REVISION 60
#define APP_VERSION_RELEASE_TYPE "Alpha"

#endif // VERSION_H
