#
# Copyright (C) 2013-2015 University of Amsterdam
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

.checkPackages <- function() {

	expected <- matrix(nrow=0, ncol=2, dimnames=list(NULL, c("Package", "Version")))

	expected <- rbind(expected, c("AER","1.2-5"))
	expected <- rbind(expected, c("Amelia","1.7.4"))
	expected <- rbind(expected, c("BB","2014.10-1"))
	expected <- rbind(expected, c("BH","1.62.0-1"))
	expected <- rbind(expected, c("BMS","0.3.4"))
	expected <- rbind(expected, c("BayesFactor","0.9.12-2"))
	expected <- rbind(expected, c("CARBayes","4.7"))
	expected <- rbind(expected, c("CARBayesdata","2.0"))
	expected <- rbind(expected, c("DBI","0.6-1"))
	expected <- rbind(expected, c("DEoptimR","1.0-8"))
	expected <- rbind(expected, c("DiagrammeR","0.9.0"))
	expected <- rbind(expected, c("Fahrmeir","2016.5.31"))
	expected <- rbind(expected, c("Formula","1.2-1"))
	expected <- rbind(expected, c("GPArotation","2014.11-1"))
	expected <- rbind(expected, c("HSAUR","1.3-7"))
	expected <- rbind(expected, c("HSAUR2","1.1-15"))
	expected <- rbind(expected, c("Hmisc","4.0-2"))
	expected <- rbind(expected, c("ISwR","2.0-7"))
	expected <- rbind(expected, c("KernSmooth","2.23-15"))
	expected <- rbind(expected, c("LearnBayes","2.15"))
	expected <- rbind(expected, c("MASS","7.3-45"))
	expected <- rbind(expected, c("MBESS","4.2.0"))
	expected <- rbind(expected, c("MCMCglmm","2.24"))
	expected <- rbind(expected, c("MCMCpack","1.3-9"))
	expected <- rbind(expected, c("MEMSS","0.9-2"))
	expected <- rbind(expected, c("Matrix","1.2-8"))
	expected <- rbind(expected, c("MatrixModels","0.4-1"))
	expected <- rbind(expected, c("NMF","0.20.6"))
	expected <- rbind(expected, c("OpenMx","2.7.9"))
	expected <- rbind(expected, c("PKPDmodels","0.3.2"))
	expected <- rbind(expected, c("R.cache","0.12.0"))
	expected <- rbind(expected, c("R.methodsS3","1.7.1"))
	expected <- rbind(expected, c("R.oo","1.21.0"))
	expected <- rbind(expected, c("R.rsp","0.40.0"))
	expected <- rbind(expected, c("R.utils","2.5.0"))
	expected <- rbind(expected, c("R6","2.2.0"))
	expected <- rbind(expected, c("RColorBrewer","1.1-2"))
	expected <- rbind(expected, c("RJSONIO","1.3-0"))
	expected <- rbind(expected, c("RSVGTipsDevice","1.0-7"))
	expected <- rbind(expected, c("RUnit","0.4.31"))
	expected <- rbind(expected, c("Rcgmin","2013-2.21"))
	expected <- rbind(expected, c("Rcmdr","2.3-2"))
	expected <- rbind(expected, c("RcmdrMisc","1.0-5"))
	expected <- rbind(expected, c("Rcpp","0.12.10"))
	expected <- rbind(expected, c("RcppArmadillo","0.7.700.0.0"))
	expected <- rbind(expected, c("RcppEigen","0.3.2.9.1"))
	expected <- rbind(expected, c("Rcsdp","0.1.55"))
	expected <- rbind(expected, c("Rook","1.1-1"))
	expected <- rbind(expected, c("Rvmmin","2013-11.12"))
	expected <- rbind(expected, c("SimComp","2.2"))
	expected <- rbind(expected, c("Sleuth2","2.0-4"))
	expected <- rbind(expected, c("SparseM","1.76"))
	expected <- rbind(expected, c("StanHeaders","2.14.0-1"))
	expected <- rbind(expected, c("SuppDists","1.1-9.4"))
	expected <- rbind(expected, c("TH.data","1.0-8"))
	expected <- rbind(expected, c("VGAM","1.0-3"))
	expected <- rbind(expected, c("XML","3.98-1.6"))
	expected <- rbind(expected, c("abind","1.4-5"))
	expected <- rbind(expected, c("acepack","1.4.1"))
	expected <- rbind(expected, c("afex","0.16-1"))
	expected <- rbind(expected, c("alr4","1.0.5"))
	expected <- rbind(expected, c("ape","4.1"))
	expected <- rbind(expected, c("arm","1.9-3"))
	expected <- rbind(expected, c("ascii","2.1"))
	expected <- rbind(expected, c("assertthat","0.1"))
	expected <- rbind(expected, c("backports","1.0.5"))
	expected <- rbind(expected, c("base","3.3.3"))
	expected <- rbind(expected, c("base64enc","0.1-3"))
	expected <- rbind(expected, c("bdsmatrix","1.3-2"))
	expected <- rbind(expected, c("bitops","1.0-6"))
	expected <- rbind(expected, c("boot","1.3-18"))
	expected <- rbind(expected, c("brew","1.0-6"))
	expected <- rbind(expected, c("ca","0.70"))
	expected <- rbind(expected, c("caTools","1.17.1"))
	expected <- rbind(expected, c("calibrator","1.2-6"))
	expected <- rbind(expected, c("car","2.1-4"))
	expected <- rbind(expected, c("checkmate","1.8.2"))
	expected <- rbind(expected, c("class","7.3-14"))
	expected <- rbind(expected, c("cluster","2.0.6"))
	expected <- rbind(expected, c("coda","0.19-1"))
	expected <- rbind(expected, c("codetools","0.2-15"))
	expected <- rbind(expected, c("coin","1.1-3"))
	expected <- rbind(expected, c("colorspace","1.3-2"))
	expected <- rbind(expected, c("compiler","3.3.3"))
	expected <- rbind(expected, c("contfrac","1.1-10"))
	expected <- rbind(expected, c("conting","1.6"))
	expected <- rbind(expected, c("corpcor","1.6.9"))
	expected <- rbind(expected, c("covr","2.2.2"))
	expected <- rbind(expected, c("coxme","2.2-5"))
	expected <- rbind(expected, c("crayon","1.3.2"))
	expected <- rbind(expected, c("cubature","1.3-6"))
	expected <- rbind(expected, c("curl","2.4"))
	expected <- rbind(expected, c("d3Network","0.5.2.1"))
	expected <- rbind(expected, c("data.table","1.10.4"))
	expected <- rbind(expected, c("datasets","3.3.3"))
	expected <- rbind(expected, c("deSolve","1.14"))
	expected <- rbind(expected, c("deldir","0.1-12"))
	expected <- rbind(expected, c("dfoptim","2016.7-1"))
	expected <- rbind(expected, c("dichromat","2.0-0"))
	expected <- rbind(expected, c("digest","0.6.12"))
	expected <- rbind(expected, c("diptest","0.75-7"))
	expected <- rbind(expected, c("doMC","1.3.4"))
	expected <- rbind(expected, c("doParallel","1.0.10"))
	expected <- rbind(expected, c("dplyr","0.5.0"))
	expected <- rbind(expected, c("e1071","1.6-8"))
	expected <- rbind(expected, c("effects","3.1-2"))
	expected <- rbind(expected, c("ellipse","0.3-8"))
	expected <- rbind(expected, c("elliptic","1.3-7"))
	expected <- rbind(expected, c("emulator","1.2-15"))
	expected <- rbind(expected, c("estimability","1.2"))
	expected <- rbind(expected, c("evaluate","0.10"))
	expected <- rbind(expected, c("expm","0.999-2"))
	expected <- rbind(expected, c("fdrtool","1.2.15"))
	expected <- rbind(expected, c("flexmix","2.3-13"))
	expected <- rbind(expected, c("foreach","1.4.3"))
	expected <- rbind(expected, c("foreign","0.8-67"))
	expected <- rbind(expected, c("fpc","2.1-10"))
	expected <- rbind(expected, c("gamm4","0.2-4"))
	expected <- rbind(expected, c("gbm","2.1.3"))
	expected <- rbind(expected, c("gdata","2.17.0"))
	expected <- rbind(expected, c("gdtools","0.1.4"))
	expected <- rbind(expected, c("gee","4.13-19"))
	expected <- rbind(expected, c("geepack","1.2-1"))
	expected <- rbind(expected, c("ggm","2.3"))
	expected <- rbind(expected, c("ggplot2","2.2.1"))
	expected <- rbind(expected, c("ggplot2movies","0.0.1"))
	expected <- rbind(expected, c("glasso","1.8"))
	expected <- rbind(expected, c("gmodels","2.16.2"))
	expected <- rbind(expected, c("gnm","1.0-8"))
	expected <- rbind(expected, c("grDevices","3.3.3"))
	expected <- rbind(expected, c("graphics","3.3.3"))
	expected <- rbind(expected, c("grid","3.3.3"))
	expected <- rbind(expected, c("gridBase","0.4-7"))
	expected <- rbind(expected, c("gridExtra","2.2.1"))
	expected <- rbind(expected, c("gsl","1.9-10.3"))
	expected <- rbind(expected, c("gtable","0.2.0"))
	expected <- rbind(expected, c("gtools","3.5.0"))
	expected <- rbind(expected, c("heplots","1.3-3"))
	expected <- rbind(expected, c("hexbin","1.27.1"))
	expected <- rbind(expected, c("highr","0.6"))
	expected <- rbind(expected, c("hms","0.3"))
	expected <- rbind(expected, c("htmlTable","1.9"))
	expected <- rbind(expected, c("htmltools","0.3.5"))
	expected <- rbind(expected, c("htmlwidgets","0.8"))
	expected <- rbind(expected, c("httpuv","1.3.3"))
	expected <- rbind(expected, c("httr","1.2.1"))
	expected <- rbind(expected, c("huge","1.2.7"))
	expected <- rbind(expected, c("hypergeo","1.2-13"))
	expected <- rbind(expected, c("igraph","1.0.1"))
	expected <- rbind(expected, c("influenceR","0.1.0"))
	expected <- rbind(expected, c("inline","0.3.14"))
	expected <- rbind(expected, c("irlba","2.1.2"))
	expected <- rbind(expected, c("iterators","1.0.8"))
	expected <- rbind(expected, c("itertools","0.1-3"))
	expected <- rbind(expected, c("jpeg","0.1-8"))
	expected <- rbind(expected, c("jsonlite","1.3"))
	expected <- rbind(expected, c("kernlab","0.9-25"))
	expected <- rbind(expected, c("kknn","1.3.1"))
	expected <- rbind(expected, c("knitr","1.15.1"))
	expected <- rbind(expected, c("labeling","0.3"))
	expected <- rbind(expected, c("languageR","1.4.1"))
	expected <- rbind(expected, c("lattice","0.20-34"))
	expected <- rbind(expected, c("latticeExtra","0.6-28"))
	expected <- rbind(expected, c("lavaan","0.5-23.1097"))
	expected <- rbind(expected, c("lazyeval","0.2.0"))
	expected <- rbind(expected, c("leaps","3.0"))
	expected <- rbind(expected, c("lme4","1.1-12"))
	expected <- rbind(expected, c("lmerTest","2.0-33"))
	expected <- rbind(expected, c("lmtest","0.9-35"))
	expected <- rbind(expected, c("logspline","2.1.9"))
	expected <- rbind(expected, c("lpSolve","5.6.13"))
	expected <- rbind(expected, c("lsmeans","2.25-5"))
	expected <- rbind(expected, c("magrittr","1.5"))
	expected <- rbind(expected, c("mapproj","1.2-4"))
	expected <- rbind(expected, c("maps","3.1.1"))
	expected <- rbind(expected, c("maptools","0.9-2"))
	expected <- rbind(expected, c("markdown","0.7.7"))
	expected <- rbind(expected, c("matrixcalc","1.0-3"))
	expected <- rbind(expected, c("mclust","5.2.3"))
	expected <- rbind(expected, c("mcmc","0.9-4"))
	expected <- rbind(expected, c("mediation","4.4.5"))
	expected <- rbind(expected, c("methods","3.3.3"))
	expected <- rbind(expected, c("mgcv","1.8-17"))
	expected <- rbind(expected, c("mi","1.0"))
	expected <- rbind(expected, c("mice","2.30"))
	expected <- rbind(expected, c("mime","0.5"))
	expected <- rbind(expected, c("miniUI","0.1.1"))
	expected <- rbind(expected, c("minqa","1.2.4"))
	expected <- rbind(expected, c("mlmRev","1.0-6"))
	expected <- rbind(expected, c("mnormt","1.5-5"))
	expected <- rbind(expected, c("modeltools","0.2-21"))
	expected <- rbind(expected, c("mratios","1.3.17"))
	expected <- rbind(expected, c("multcomp","1.4-6"))
	expected <- rbind(expected, c("multcompView","0.1-7"))
	expected <- rbind(expected, c("munsell","0.4.3"))
	expected <- rbind(expected, c("mvtnorm","1.0-6"))
	expected <- rbind(expected, c("network","1.13.0"))
	expected <- rbind(expected, c("nlme","3.1-131"))
	expected <- rbind(expected, c("nloptr","1.0.4"))
	expected <- rbind(expected, c("nnet","7.3-12"))
	expected <- rbind(expected, c("numDeriv","2016.8-1"))
	expected <- rbind(expected, c("openssl","0.9.6"))
	expected <- rbind(expected, c("optextras","2016-8.8"))
	expected <- rbind(expected, c("optimx","2013.8.7"))
	expected <- rbind(expected, c("ordinal","2015.6-28"))
	expected <- rbind(expected, c("parallel","3.3.3"))
	expected <- rbind(expected, c("pbapply","1.3-2"))
	expected <- rbind(expected, c("pbivnorm","0.6.0"))
	expected <- rbind(expected, c("pbkrtest","0.4-7"))
	expected <- rbind(expected, c("permute","0.9-4"))
	expected <- rbind(expected, c("pixmap","0.4-11"))
	expected <- rbind(expected, c("pkgKitten","0.1.4"))
	expected <- rbind(expected, c("pkgmaker","0.22"))
	expected <- rbind(expected, c("plotrix","3.6-4"))
	expected <- rbind(expected, c("plyr","1.8.4"))
	expected <- rbind(expected, c("png","0.1-7"))
	expected <- rbind(expected, c("poLCA","1.4.1"))
	expected <- rbind(expected, c("polycor","0.7-9"))
	expected <- rbind(expected, c("prabclus","2.2-6"))
	expected <- rbind(expected, c("praise","1.0.0"))
	expected <- rbind(expected, c("pscl","1.4.9"))
	expected <- rbind(expected, c("psych","1.7.3.21"))
	expected <- rbind(expected, c("qgraph","1.4.3"))
	expected <- rbind(expected, c("quadprog","1.5-5"))
	expected <- rbind(expected, c("quantreg","5.29"))
	expected <- rbind(expected, c("qvcalc","0.9-0"))
	expected <- rbind(expected, c("randomForest","4.6-12"))
	expected <- rbind(expected, c("readxl","0.1.1"))
	expected <- rbind(expected, c("registry","0.3"))
	expected <- rbind(expected, c("relimp","1.0-5"))
	expected <- rbind(expected, c("reshape2","1.4.2"))
	expected <- rbind(expected, c("rex","1.1.1"))
	expected <- rbind(expected, c("rgexf","0.15.3"))
	expected <- rbind(expected, c("rgl","0.98.1"))
	expected <- rbind(expected, c("rjson","0.2.15"))
	expected <- rbind(expected, c("rmarkdown","1.4"))
	expected <- rbind(expected, c("rngtools","1.2.4"))
	expected <- rbind(expected, c("robustbase","0.92-7"))
	expected <- rbind(expected, c("rpart","4.1-10"))
	expected <- rbind(expected, c("rpf","0.53"))
	expected <- rbind(expected, c("rprojroot","1.2"))
	expected <- rbind(expected, c("rsm","2.8"))
	expected <- rbind(expected, c("rstudioapi","0.6"))
	expected <- rbind(expected, c("rtiff","1.4.5"))
	expected <- rbind(expected, c("sandwich","2.3-4"))
	expected <- rbind(expected, c("scales","0.4.1"))
	expected <- rbind(expected, c("scatterplot3d","0.3-39"))
	expected <- rbind(expected, c("sem","3.1-8"))
	expected <- rbind(expected, c("semTools","0.4-14"))
	expected <- rbind(expected, c("sendplot","4.0.0"))
	expected <- rbind(expected, c("setRNG","2013.9-1"))
	expected <- rbind(expected, c("shapefiles","0.7"))
	expected <- rbind(expected, c("shiny","1.0.1"))
	expected <- rbind(expected, c("shinyjs","0.9"))
	expected <- rbind(expected, c("sna","2.4"))
	expected <- rbind(expected, c("sourcetools","0.1.5"))
	expected <- rbind(expected, c("sp","1.2-4"))
	expected <- rbind(expected, c("spam","1.4-0"))
	expected <- rbind(expected, c("spatial","7.3-11"))
	expected <- rbind(expected, c("spdep","0.6-11"))
	expected <- rbind(expected, c("splines","3.3.3"))
	expected <- rbind(expected, c("statnet.common","3.3.0"))
	expected <- rbind(expected, c("stats","3.3.3"))
	expected <- rbind(expected, c("stats4","3.3.3"))
	expected <- rbind(expected, c("stringi","1.1.3"))
	expected <- rbind(expected, c("stringr","1.2.0"))
	expected <- rbind(expected, c("survey","3.31-5"))
	expected <- rbind(expected, c("survival","2.40-1"))
	expected <- rbind(expected, c("svUnit","0.7-12"))
	expected <- rbind(expected, c("svglite","1.2.0"))
	expected <- rbind(expected, c("tcltk","3.3.3"))
	expected <- rbind(expected, c("tcltk2","1.2-11"))
	expected <- rbind(expected, c("tensorA","0.36"))
	expected <- rbind(expected, c("testthat","1.0.2"))
	expected <- rbind(expected, c("tibble","1.3.0"))
	expected <- rbind(expected, c("tools","3.3.3"))
	expected <- rbind(expected, c("trimcluster","0.1-2"))
	expected <- rbind(expected, c("truncnorm","1.0-7"))
	expected <- rbind(expected, c("tseries","0.10-38"))
	expected <- rbind(expected, c("ucminf","1.1-4"))
	expected <- rbind(expected, c("utils","3.3.3"))
	expected <- rbind(expected, c("vcd","1.4-3"))
	expected <- rbind(expected, c("vcdExtra","0.7-0"))
	expected <- rbind(expected, c("vegan","2.4-2"))
	expected <- rbind(expected, c("viridis","0.4.0"))
	expected <- rbind(expected, c("viridisLite","0.2.0"))
	expected <- rbind(expected, c("visNetwork","1.0.3"))
	expected <- rbind(expected, c("whisker","0.3-2"))
	expected <- rbind(expected, c("withr","1.0.2"))
	expected <- rbind(expected, c("xtable","1.8-2"))
	expected <- rbind(expected, c("yaml","2.1.14"))
	expected <- rbind(expected, c("zoo","1.7-14"))

	expected.package.names <- expected[,1]
	dimnames(expected) <- list(expected.package.names, c("Package", "Version"))

	installed <- installed.packages()
	installed.package.names <- dimnames(installed)[[1]]

	messages <- c()

	for (package.name in expected.package.names) {
	
		if (package.name %in% installed.package.names) {
		
			installed.version <- installed[package.name, "Version"]
			expected.version  <- expected[package.name, "Version"]
		
			if (installed.version != expected.version)
				messages <- c(messages, paste("Package ", package.name, " is not the correct version; expected: ", expected.version, ", installed: ", installed.version, sep=""))
		
		} else {
		
			messages <- c(messages, paste("Package ", package.name, " not installed!", sep=""))
		}
	
	}
	
	.initPackages(installed.package.names)
	
	if (length(messages) == 0) {
	
		list(official=TRUE)
	
	} else {
	
		list(official=FALSE, messages=messages)
	}
}


.initPackages <- function(installedPackages) {
	
	packages <- c("BayesFactor") # Add any package that needs pre-loading
	
	for (package in packages) {
		if (package %in% installedPackages && base::isNamespaceLoaded(package) == FALSE) {
			try(base::loadNamespace(package), silent=TRUE)
		}
	}
	
}

